<?php

namespace common\models;

use Yii;
use \yii\web\UploadedFile;
use common\models\User;
use yii\validators\FileValidator;

/**
 * This is the model class for table "profile".
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $filefoto
 *
 * @property User $user
 * @property ProfileFields[] $profileFields
 */
class Profile extends \yii\db\ActiveRecord
{
    public $image;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'profile';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['image'], 'safe'],
            [['image'], 'file', 'extensions' => 'png,jpg,jpeg'],
            [['user_id'], 'required'],
            [['user_id'], 'integer'],
            [['filefoto'], 'string', 'max' => 256],
            [['user_id'], 'unique'],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'filefoto' => 'Filefoto',
        ];
    }
    public function init()
    {
        $this->user_id = Yii::$app->user->id;
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProfileFields()
    {
        return $this->hasMany(ProfileFields::className(), ['profile_id' => 'id']);
    }

    public function beforeSave($insert)
    {



        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    public function validate($attributeNames = null, $clearErrors = true)
    {
        if(isset($this->image)){
            $_image = UploadedFile::getInstance($this,'image');
            if(is_object($_image)){
                $name = Yii::$app->basePath . '/web/upload/';  //set directory path to save image
                $_fileName =  $this->image;
                $ext = explode(".",$_image->name);
                $_ext = $ext[count($ext)-1];

                $this->filefoto=Yii::$app->security->generateRandomString().".{$_ext}";
                $_res = $_image->saveAs($name.$this->filefoto,$_image);

                if (!$_res){
                    $this->addError('image',['error' => 'Error!']);
                }
                // $_image = $this->inv_id."_".$this->image;    //appending id to image name
                //       Yii::$app->db->createCommand()
                //         ->update('invoice', ['image' => $this->image], 'inv_id = "'.$this->inv_id.'"')
                //       ->execute(); //manually update image name to db
            }
        }


        return parent::validate($attributeNames, $clearErrors); // TODO: Change the autogenerated stub
    }
}
